name: mappymatch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - osmnx
  - geopandas
  - shapely
  - rtree
  - pyproj
  - pandas
  - numpy
  - matplotlib
  - folium
  - requests
  - pip
  - pip:
    - -e . 
    - sphinx-autobuild=2021.3.14
  - pytest
  - sphinx=4.5.0
  - sphinx_rtd_theme=1.0.0
  - sphinxemoji==0.2.0
  - pre-commit
  - black
  - isort
  - interrogate
  - coverage
  - mypy
